version: '2.1'

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:19.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -DskipTests

orbs:
  maven: circleci/maven@1.4.0
  tcc: atomicjar/testcontainers-cloud-orb@0.1.0

executors:
  j19:
    docker:
      - image: 'cimg/openjdk:19.0'
#  machine_executor_amd64:
#    machine:
#      image: ubuntu-2204:2022.04.2
#    environment:
#      architecture: "amd64"
#      platform: "linux/amd64"

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j19
          context: Testcontainers
      - analyze:
          context: SonarCloud